config/routes.rb
SwagFm::Application.routes.draw do

  resources :oauth_clients
  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request
  match '/oauth/token',         :to => 'oauth#token',         :as => :token
  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token
  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token
  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize
  match '/oauth',               :to => 'oauth#index',         :as => :oauth

  resource :session, controller: 'session'
  resources :users
  resources :tracks, only: %w[index create update destroy]
  resources :favorites, only: %w[index create update destroy]

  resources :extensions, only: [] do
    get :chrome, on: :collection
  end

  root to: 'tracks#index'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  attr_accessible :track, :user, :position

  #################
  ### Relations ###
  #################

  belongs_to :user
  belongs_to :track
  belongs_to :from_user

  ###################
  ### Validations ###
  ###################

  validates :user, :track, :position, presence: true

  #####################
  ### Class methods ###
  #####################

  def self.new_from_url(url)
    new(track: Track.find_by_url(url) || Track.new_from_url(url))
  end

  def self.between(from, to)
    where('position BETWEEN ? AND ?', from, to)
  end

  ######################
  ### Public methods ###
  ######################

  def reorder(new_position)
    return if new_position == position
    Favorite.transaction do
      if new_position < position
        user.favorites.between(new_position, position).update_all('position = position + 1')
      else
        user.favorites.between(position, new_position).update_all('position = position - 1')
      end
      update_attributes!(position: new_position)
    end
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :url

  #####################
  ### Class methods ###
  #####################

  def self.from_url(url)
    player = new(url: url) and player.fetch_metadata and player
  end

  ######################
  ### Public methods ###
  ######################

  def fetch_metadata
    require 'swag_fm'
    if track = SwagFm.official.track(resource_id, fields: 'cover')
      self.cover_url = track.cover.urls.medium
      self.stream_url = track.streaming.http
    end
  end

  def resource_id
    url.split('/').last
  end

  def resource_type
    url.split('/')[-2]
  end
end

app/models/track.rb
class Track < ActiveRecord::Base

  attr_accessible :url

  #################
  ### Relations ###
  #################

  has_many :favorites

  ###################
  ### Validations ###
  ###################

  validate :title, :artist, :duration, :url, :stream_url, :cover_url, presence: true

  #####################
  ### Class methods ###
  #####################

  def self.new_from_url(url)
    track = new(url: url) and track.fetch_metadata and track
  end

  ######################
  ### Public methods ###
  ######################

  def fetch_metadata
    if resolver = SwagFm::Resolver.new_from_url(url)
      self.cover_url = resolver.cover_url
      self.stream_url = resolver.stream_url
      self.duration = resolver.duration
      self.url = resolver.origin_url
      self.artist = resolver.artist
      self.title = resolver.title
    end
  end

  def resource_id
    url.split('/').last
  end

  def resource_type
    url.split('/')[-2]
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  ##################
  ### Attributes ###
  ##################

  attr_accessible :email, :password
  has_secure_password

  #################
  ### Relations ###
  #################

  has_many :favorites, order: 'position'

  ######################
  ### Public methods ###
  ######################

  def name
    email.split('@').first
  end

  def add_favorite(favorite)
    User.transaction do
      favorites.update_all('position = position + 1')
      favorite.position = 1 and favorite.user = self
      favorite.save or raise ActiveRecord::Rollback
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_user=(user)
    session[:user_id] = (@current_user = user).try(:id)
  end

  def login_required
    #TODO
  end

  def logged_in?
    current_user
  end
end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController

  def chrome
    @appid = 'cdhdajhnhngfaejfecmehacdbeamomio'
    @codebase = 'http://dl.dropbox.com/s/uuwldfs2yiykzm8/swagfm_v0.3.crx?dl=1'
    @version = '0.2'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @user = current_user
    @favorite = Favorite.new_from_url(params[:url])
    if current_user.add_favorite(@favorite)
      respond_to do |format|
        format.html { render(layout: false) }
        format.json { render(json: @favorite) }
      end
    else
      render(@favorite.errors, status: :unprocessable_entity)
    end
  end

  def update
    current_user.favorites.find(params[:id]).reorder(params[:position].to_i)
    render(text: 'OK')
  end

  def destroy
    current_user.favorites.find(params[:id]).destroy
    head(:no_content)
  end

end

app/controllers/players_controller_controller.rb
# -*- encoding : utf-8 -*-

class PlayersControllerController < ApplicationController

  def create
    @player = Player.new(params[:player])
    if @player.save
      render json: @player
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def show
  end

  def create
    email, password = params[:session][:email], params[:session][:password]
    if self.current_user = User.find_by_email(email).try(:authenticate, password) || nil
      respond_to do |format|
        format.html { redirect_to(current_user) }
        format.json { render json: {} }
      end
    else
      render(:show)
    end
  end

  def destroy
    self.current_user = nil
    redirect_to('/')
  end
end

app/controllers/tracks_controller.rb
# -*- encoding : utf-8 -*-

class TracksController < ApplicationController

  def create
    @user = current_user
    @track = Track.from_url(params[:url])
    if current_user.add_track(@track)
      if @track.save
        respond_to do |format|
          format.html { render(layout: false) }
          format.json { render json: @track }
        end
      else
        render @track.errors, status: :unprocessable_entity
      end
    else
      render text: 'This track does not exist.', status: :unprocessable_entity
    end
  end

  def index
    @tracks = Track.limit(100).order('created_at DESC')
    respond_to do |format|
      format.html { render }
      format.json { render json: @tracks = Track.where(url: params[:url]) }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    redirect_to(self.current_user = User.create!(params[:user]))
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/players_controller_helper.rb
module PlayersControllerHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
  def track_tooltip(track)
    "#{track.artist} - #{track.title}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/extensions/chrome.xml.erb
<?xml version='1.0' encoding='UTF-8'?>
<gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
  <app appid='<%= @appid %>'>
    <updatecheck codebase='<%= @codebase %>' version='<%= @version %>' />
  </app>
</gupdate>

app/views/favorites/_favorite.html.erb
<div
  id="favorite_<%= favorite.id %>"
  class="track favorite"
  data-track-id="<%= favorite.track.id %>"
  data-url="<%= favorite_url(favorite) %>"
  data-position="<%= favorite.position %>"
  data-stream-url="<%= favorite.track.stream_url %>"
  data-origin-url="<%= favorite.track.url %>"
  data-title="<%= favorite.track.title %>"
  data-artist="<%= favorite.track.artist %>"
  style="background-image: url('<%= favorite.track.cover_url %>')">
  <div class="details">
    <span class="title"><%= favorite.track.title %></span><br/>
    <span class="artist"><%= favorite.track.artist %></span>
  </div>
  <div class="primary controls">
    <span class="iconic play" data-action="play" data-target="favorite_<%= favorite.id %>" title="Play"></span>
    <span class="iconic pause" data-action="pause" data-target="favorite_<%= favorite.id %>" title="Pause"></span>
  </div>
  <div class="secondary controls">
    <% if current_user && current_user == @user %>
      <span class="iconic trash_stroke" data-action="delete" data-target="favorite_<%= favorite.id %>" title="Delete"></span>
      <span class="iconic move" data-action="move" data-target="favorite_<%= favorite.id %>" draggable="true" title="Move"></span>
    <% end %>
    <% if current_user && current_user != @user %>
      <span class="iconic plus" data-action="import" data-target="favorite_<%= favorite.id %>" title="Import to your playlist"></span>
    <% end %>
    <a href="<%= favorite.track.url %>" class="iconic link" target="_blank" title="Official page"></a>
  </div>
</div>

app/views/favorites/create.html.erb
<%= render @favorite %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwagFm</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
  <%= yield %>
  <footer>
    <section class="controls">
      <span class="iconic first" id="previous-button" title="Previous track (use left arrow as a shortcut)"></span>
      <span class="iconic play" id="play-button" title="Play/pause (use space key as a shortcut)"></span>
      <span class="iconic last" id="next-button" title="Next track (use right arrow as a shortcut)"></span>
    </section>
    <section class="info">
      <a id="current-track" href="" title="Go to playing track"></a>
    </section>
    <section class="settings">
      <% if current_user %>
        <%= link_to 'Add', '', id: "add-button" %>
      <% end %>
      <% if @user && current_user != @user %>
        <%= link_to "#{@user.name}'s favorites", @user, class: 'active' %>
      <% end %>
      <%= link_to 'People', users_path, class: request.fullpath == users_path ? 'active' : '' %>
      <%= link_to 'Latest tracks', tracks_path, class: request.fullpath == tracks_path ? 'active' : '' %>
      <% if current_user %>
        <%= link_to 'Favorites', current_user, class: request.fullpath == user_path(current_user) ? 'active' : '' %>
        <%= link_to 'Logout', session_path, method: 'DELETE' %>
      <% else %>
        <%= link_to 'Login', session_path %>
        <%= link_to 'Signup', new_user_path %>
      <% end %>
    </section>
  </footer>
</body>
</html>

app/views/session/index.html.erb
<%= form_for :session do |form| %>
  <%= form.text_field :email, placeholder: 'Email' %>
  <%= form.password_field :password, placeholder: 'Password' %>
  <%= form.submit 'Login' %>
<% end %>

app/views/session/show.html.erb
<%= form_for :session do |form| %>
  <%= form.text_field :email, placeholder: 'Email' %>
  <%= form.password_field :password, placeholder: 'Password' %>
  <%= form.submit 'Login' %>
<% end %>

app/views/tracks/_track.html.erb
<div
  id="track_<%= track.id %>"
  class="track"
  data-track-id="<%= track.id %>"
  data-url="<%= track_url(track) %>"
  data-stream-url="<%= track.stream_url %>"
  data-origin-url="<%= track.url %>"
  data-title="<%= track.title %>"
  data-artist="<%= track.artist %>"
  style="background-image: url('<%= track.cover_url %>')">
  <div class="details">
    <span class="title"><%= track.title %></span><br/>
    <span class="artist"><%= track.artist %></span>
  </div>
  <div class="primary controls">
    <span class="iconic play" data-action="play" data-target="track_<%= track.id %>" title="Play"></span>
    <span class="iconic pause" data-action="pause" data-target="track_<%= track.id %>" title="Pause"></span>
  </div>
  <div class="secondary controls">
    <% if current_user && current_user == @user %>
      <span class="iconic trash_stroke" data-action="delete" data-target="track_<%= track.id %>" title="Delete"></span>
      <span class="iconic move" data-action="move" data-target="track_<%= track.id %>" draggable="true" title="Move"></span>
    <% end %>
    <% if current_user && current_user != @user %>
      <span class="iconic plus" data-action="import" data-target="track_<%= track.id %>" title="Import to your playlist"></span>
    <% end %>
    <a href="<%= track.url %>" class="iconic link" target="_blank" title="Official page"></a>
  </div>
</div>

app/views/tracks/index.html.erb
<section class="tracks">
  <%= render @tracks %>
</section>

app/views/users/index.html.erb
<h1>Discover music listened by other swag users !</h1>

<section class="users">
  <% for user in @users %>
    <%= link_to user.name, user %> <span class="track-count">(<%= user.favorites.count %> favorites)</span><br/>
  <% end %>
</section>

app/views/users/new.html.erb
<%= form_for User.new do |form| %>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= form.label :password %>
  <%= form.password_field :password %>
  <%= form.submit 'Signup' %>
<% end %>

app/views/users/show.html.erb
<section class="tracks">
  <%= render @user.favorites %>

  <% if current_user == @user %>
    <% if @user.favorites.empty? %>
      <div class="blank slate">
        Copy a URL from a track hosted on Official.fm or Soundcloud.com, then click on the plus button below to paste it !
      </div>
    <% end %>
  <% end %>

  <% if @user.favorites.empty? && @user != current_user %>
    <h2>Too bad ... that user doesn't have any favorites yet :-(</h2>
  <% end %>
</section>